### ISSUE TITLE
Change to filamentOdometer broke PrintJobHistory

### ISSUE THREAD

**Issue by RealDeuce** [OllisGit/OctoPrint-FilamentManager#44]
**Describe the bug**
PrintJobHistory (https://github.com/OllisGit/OctoPrint-PrintJobHistory/) uses the filamentOdometer previously exposed by this plugin, but with the rename to myFilamentOdometer, PrintJobHistory now fails to log new prints.

**Steps to reproduce**
1. Install PrintJobHistory
2. Print
3. See error in log

**Expected behavior**
Plugins which depend on FilamentManger should continue to work.

**Did the same happen when all other 3rd party plugins are disabled?**
Issue cause by PrintJobHistory

**Log file**
```
2021-02-16 22:10:11,936 - octoprint.plugin - ERROR - Error while calling plugin PrintJobHistory
Traceback (most recent call last):
  File "/home/octoprint/OctoPrint/venv/lib/python3.8/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/octoprint/OctoPrint/venv/lib/python3.8/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/octoprint/OctoPrint/venv/lib/python3.8/site-packages/octoprint_PrintJobHistory/__init__.py", line 614, in on_event
    self._printJobFinished("success", payload)
  File "/home/octoprint/OctoPrint/venv/lib/python3.8/site-packages/octoprint_PrintJobHistory/__init__.py", line 436, in _printJobFinished
    self._createAndAssignFilamentModel(self._currentPrintJobModel, payload)
  File "/home/octoprint/OctoPrint/venv/lib/python3.8/site-packages/octoprint_PrintJobHistory/__init__.py", line 254, in _createAndAssignFilamentModel
    filemanentModel.usedLength = self._filamentManagerPluginImplementation.filamentOdometer.totalExtrusion[0]
AttributeError: 'FilamentManagerPlugin' object has no attribute 'filamentOdometer'
2021-02-16 22:10:11,938 - octoprint.plugins.filamentmanager - INFO - Updating Filament usage for octoprint configured toolcount: 1
2021-02-16 22:10:11,938 - octoprint.plugins.filamentmanager - INFO - Filament tracked toolcount: 1
2021-02-16 22:10:11,938 - octoprint.plugins.filamentmanager - INFO - Filament tracked values: [678.7383200000065]
2021-02-16 22:10:11,938 - octoprint.plugins.filamentmanager - INFO - Filament used: 678.7383200000065 mm (tool0)
```

**Additional context**
Wasn't sure if I should file this here or in PrintJobHistory... I went with here since the breaking change was here.

**Comment by OllisGit** [comment]
Fixed with V1.7.2
