### ISSUE TITLE
Doc update: reinstall FM if OS update causes flask errors

### ISSUE THREAD

**Issue by jacix** [OllisGit/OctoPrint-FilamentManager#73]
After I updated the OS on my Raspi4, FilamentManager (which I love, by the way!) complained of an error when I tried to change spools - log entry is pasted below.  Testing the connection to Postgres didn't turn the button red or green, which was odd, but I was able to connect with psql, so I knew the database was running and healthy. 
Reinstalling Filament manager solved it, so that would be a good addition to the docs.  

> 2021-07-17 18:05:13,211 - octoprint.plugins.filamentmanager - WARNING - self.filamentManager is not initialized yet
2021-07-17 18:05:13,212 - octoprint - ERROR - Exception on /plugin/filamentmanager/database/test [POST]
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement

**Comment by OllisGit** [comment]
Hi @jacix,

I received a PR that output the connection result directly in the uI (https://github.com/OllisGit/OctoPrint-FilamentManager/pull/77) ... maybe it improves your case.

Next time, please add the full octoprint.log, because it looks like that the FM-API was called but the Plugin-Initialization was not ready or broke down previously.
