### ISSUE TITLE
Cannot add profiles

### ISSUE THREAD

**Issue by berserk88** [OllisGit/OctoPrint-FilamentManager#97]
Cannot add profiles. When I click save in the add profile screen I get the following error: Could not add profile. There was an unexpected error while saving the filament profile, please consult the log files.

**Log file**
2022-03-02 09:19:00,133 - octoprint.plugins.filamentmanager - WARNING - self.filamentManager is not initialized yet
2022-03-02 09:19:00,134 - octoprint - ERROR - Exception on /plugin/filamentmanager/profiles [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement

**Comment by JernejL** [comment]
I have this same problem - no success with this plugin, fails when adding profile. 
 
`2022-09-09 11:12:06,005 - octoprint.plugins.filamentmanager - WARNING - self.filamentManager is not initialized yet
2022-09-09 11:12:06,007 - octoprint - ERROR - Exception on /plugin/filamentmanager/profiles [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
`
